mirror-media/plate-vue

src/components/Header.vue
src/components/LatestProject.vue
src/components/Leading.vue
src/components/Loading.vue
src/constants/index.js
src/router/index.js
src/store/api.js
src/store/index.js
src/views/Home.vue
src/views/List.vue

- integrate List Style Page (Section, Category, Topic)
- add Loading Component (Loading Effect at Home Page)
- add Leading Component for Topic (not finish)
- adjust Header, LatestProject Style

integrate List Style Page & add Loading Component

---

src/components/Footer.vue
src/components/Leading.vue
src/components/Slider.vue
src/components/article/ArticleBody.vue
src/components/article/PopList.vue
src/components/article/ProjectList.vue
src/components/article/RelatedList.vue
src/components/article/RelatedListOneCol.vue
src/components/article/ShareTools.vue
src/views/Article.vue

implement tablet layout for single column article page(not including photography yet)
implement poplist mobile layout on article page
implment article page mobile layout(not including photography yet)

implment article page mobile layout(not including photography yet)

---

src/App.vue
src/components/Footer.vue
src/components/article/ArticleBody.vue
src/components/article/RelatedList.vue
src/store/api.js
src/utils/comm.js
src/views/Article.vue

change the way to fetch host info

---

api/index.js
src/App.vue
src/components/AudioList.vue
src/components/Header.vue
src/components/VideoList.vue
src/store/api.js
src/store/index.js
src/views/Home.vue
src/views/List.vue

- add Youtube Play List API
- add Videohub Page Component
- add Audio Page Component (not finished)
- adjust Header CSS

add Videohub Page

---

api/index.js
src/components/article/ArticleBody.vue
src/store/api.js
src/views/Article.vue
src/views/Home.vue

revised the snigle column name 'wide'

adjust poplist and quesitonnaire api

---

api/index.js
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyPhotography.vue
src/components/article/PopList.vue
src/components/questionnaire/Question.vue
src/components/questionnaire/ShareToolbox.vue
src/constants/index.js
src/store/api.js
src/utils/comm.js
src/views/Article.vue
src/views/List.vue
src/views/Questionnaire.vue

add audio leading type for questionnair

fixed api for questionnair page

---

package.json
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyPhotography.vue
src/constants/index.js
src/views/Article.vue
src/views/List.vue

fixed dfp issue and credit issue on article page
fixed issue 'topic switch doesn't work well #92'
notice: have to run 'npm install' again

fixed issue 'topic switch doesn't work well #92'

---

src/components/article/ArticleBody.vue
src/components/article/ArticleBodyPhotography.vue
src/views/Article.vue

add subtitle for article
add desription for the switch button
add background mask for title
fixed the scroll issue on photography article page
fixed lalyout issue for single column(wide) article page
fixed the layout issue on article page

revised the conditions for fetch article data

---

src/components/article/ArticleBodyPhotography.vue
src/views/List.vue

add more condition to avoid fetching data again when enter the current route
improve photography article scroll performance

improve photography article scroll performance

---

src/components/EditorChoice.vue
src/components/article/PopList.vue
src/components/article/ProjectList.vue
src/views/Article.vue
src/views/Home.vue
src/views/List.vue
src/views/Questionnaire.vue

fixed slideshow issue
adjust html meta for home page and listing page

adjust the layout of poplist & projectlist on article page

---

src/components/EditorChoice.vue
src/components/Footer.vue
src/components/PopularArticles.vue
src/views/HomeB.vue

fixed homepage choice layout issue.
fixed popularList on homeb page layout issue

fixed footer popup issue.

---

api/index.js
src/components/Footer.vue
src/components/LatestArticleAside.vue
src/components/LatestArticleMain.vue
src/constants/index.js
src/store/api.js
src/store/index.js
src/views/HomeB.vue

adjusted footer behavior.
adjust dfp layout.

fetch choice, latest and grouped articles from static json file

---

src/components/LatestArticleAside.vue
src/components/LatestArticleMain.vue

fixed url issue for homeb side articles and have the section label be category if section not found

---

src/index.template.html
src/views/Article.vue
src/views/List.vue

fixed the native ad in liting and article page

give sidebar a height on header conponent

---

package.json
src/components/LatestArticleAside.vue
src/components/LatestArticleMain.vue
src/components/article/ArticleBody.vue
src/constants/index.js
src/views/Article.vue
src/views/Home.vue
src/views/HomeB.vue

fixed the native ad layout issue
add ad for homeb page mobile version
add dfp mobile ads into article page
adjust slideshow layout on article page
give slideshow image captions
just show 4 articles aside per group

fixed the infobox layout issue

---

src/components/LatestArticleAside.vue
src/components/article/ArticleBody.vue

set the default color for article which doesn't belong to any section
fixed the dfp layout issue on article page tail

adjust the image style of articles aside on homeb page

---

src/components/EditorChoice.vue
src/constants/index.js
src/views/Home.vue
src/views/HomeB.vue

fixed the mobile ad layout issue on homeb page

fiexed the section label layout issue  on choice component

---

api/index.js

NOTICE: please add "API_TIMEOUT: 2000" into config.js

set timeout for api calling

---

src/components/ArticleLeading.vue
src/components/ArticleList.vue
src/components/ArticleListFull.vue
src/components/EditorChoiceFull.vue
src/components/LatestArticleAside.vue
src/components/LatestArticleFull.vue
src/components/LatestArticleMain.vue
src/components/PopularArticles.vue
src/components/article/ArticleBody.vue
src/components/article/ProjectList.vue

remove lazy load for slideshow
fixed ISO format issue for module moment usage on listing page

add id for gtm tracking on homeb page

---

src/components/article/RelatedListWithThumbnail.vue
src/views/Article.vue

show related list if article style is wide
fixed the url issue on photography article

show related list if article style is wide

---

.eslintrc
.jshintignore
.jshintrc
package.json
server.js
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyPhotography.vue
src/constants/index.js
src/router/index.js
src/server-entry.js
src/store/index.js
src/utils/comm.js
src/utils/image-composer.js
src/views/Article.vue
src/views/Home.vue
src/views/HomeB.vue
src/views/List.vue
src/views/Questionnaire.vue
src/views/Search.vue

fixed the issue what if slot dom doesn't be rendered
gave an err handler for dfp
open eslint and run lint before every single commit

fixed the 404 handler redirecting issue

---

src/App.vue
src/components/LatestArticleAside.vue
src/components/article/ArticleBody.vue
src/index.template.html
src/router/index.js
src/views/Article.vue
src/views/Home.vue
src/views/HomeB.vue

let homeB be homeA
add caption for youtube on article page
fixed layout issue on home page

implement native video on article page

---

src/components/ArticleList.vue
src/components/DfpFixed.vue
src/components/Header.vue
src/components/HeaderFull.vue
src/router/index.js
src/views/Article.vue
src/views/Topic.vue

- add topic component
- fix search bar bug in mobile
- add fixed DFP in article Page

refactor Topic Page & fix Searchbar bug

---

src/components/article/ArticleBody.vue
src/components/article/LatestList.vue

fixed the caption issue for slideshow on article page

fixed the project url issue on article page

---

src/components/ArticleList.vue
src/components/Header.vue
src/components/article/ArticleBody.vue
src/constants/index.js
src/router/index.js
src/views/List.vue
src/views/Topic.vue

- refactor List Page
- check article title to temporarily fix algolia response bug
- adjust router & edit ArticleBody author, tag link

refactor List Page

---

npmlist.txt
package.json
src/constants/index.js
src/views/Article.vue

fixed the sytax issue on article page

reduced dfp refresh calls

---

src/components/ArticleList.vue
src/components/Footer.vue
src/views/Home.vue
src/views/List.vue

- fix Watch Page EditorChoice Bug
- adjust Footer Style
- fix Search Article Sorting

fix Watch Page EditorChoice Bug

---

src/components/LatestArticleAside.vue
src/constants/index.js
src/views/Home.vue

added ad position LMBL1 to homepage

fixed layout issue on mobile home page

---

src/components/ArticleList.vue
src/components/Footer.vue
src/index.template.html
src/views/Article.vue
src/views/List.vue

- fix mediafarmers bug
- fix /section/topic article list sorting
- change footer <a> target Attribute

fix mediafarmers bug, section/topic sorting

---

src/components/ArticleList.vue
src/store/index.js
src/views/List.vue
src/views/Topic.vue

- add Topics Vuex State
- adjust Topic Fetch Function
- fix List (section/topic) Load More
- fix Topic Slideshow Images Bug
- fix List, Topic History Back Bug

fix List, Topic Page Bug

---

package.json
src/constants/index.js
src/utils/comm.js
src/views/Article.vue
src/views/Home.vue
src/views/List.vue

implemented dfp dev mode

---

src/components/article/ArticleBodyPhotography.vue
src/components/article/RelatedListWithThumbnail.vue
src/views/Article.vue

show footer dfp ad on photography artcle page

adjust related list display on phtography article

---

src/components/EditorChoice.vue
src/components/article/ArticleBodyPhotography.vue

dont render slideshow component on mobile home page

called side-nav out on phtography article page

---

src/components/LiveStream.vue
src/store/index.js
src/views/Article.vue
src/views/Home.vue
src/views/List.vue

- add LiveStream Component
- adjust Store FetchEvent for Live Stream and Logo

renew Live Stream

---

src/router/index.js
src/views/Article.vue
src/views/Home.vue
src/views/List.vue
src/views/Search.vue
src/views/TimelineView.vue
src/views/Topic.vue

- change all page GA trigger from router to component
- send PV through mounted hook and watch hook
- add GA contentGroup setting

renew All Page GA Trigger

---

src/components/activity/ActivityNodeContent.vue
src/components/activity/ActivityNodeNav.vue
src/components/activity/ActivityNodeSlider.vue
src/views/Activity.vue

adjusted page activity mobile version style

adjusted page activity mobile version style

---

src/components/activity/ActivityNode.vue
src/components/activity/ActivityNodeSlider.vue
src/views/Activity.vue

dont scroll to next/prev page if touching on activity content div only for portrait mobile version
removed swiper on mobile version activity page

improved touchmove effect prformance

---

src/components/activity/ActivityNode.vue
src/components/activity/ActivityNodeSlider.vue
src/views/Activity.vue

//make sure the outermost div of nodes is set to position = relative
//                                 ^ 
//                .activityNode-nodeContainer
//and set transition top 1s for it

revised the way to one-page scrolling with transition-top instead of setTimeout-scroll

---

src/components/activity/ActivityNodeContent.vue
src/components/activity/ActivityNodeSlider.vue
src/views/Activity.vue

- fix og:url
- fix Image Slideshow Autoplay

fix Activity Bug (No. 2,3,4 Issue)

---

api/index.js
package.json
src/App.vue
src/store/api.js
src/store/index.js
src/utils/comm.js
src/views/Activity.vue
src/views/Topic.vue

fix Search Title
fix Section Watch Page
fixed brief markups of em/strong layout issue & meta-description em issue
have the default choice be first choice on haome page
add id for related list items on article page
adjust Audio Preload to False
foodtravel section page redesign, without condition on style
Clean console.log
Clean console.log
foodtravel section page redesign, without condition on style
foodtravel section page redesign, without condition on style
Delete comment
Fix style, and delete unused images
Delete leading import
Fix style
Delete console.log
Fix slider of foodtravel
Put the id to the constants config
adjust related list display on phtography article
show footer dfp ad on photography artcle page
opened the route 'homeb'
remove route homeb
gave ad pos size '1x1' on article …

implemented user client behavior logger and merged files from branch master

---

Jenkinsfile

patch the gcs upload dist files part

add upload gcs part in Jenkinsfile

---

Jenkinsfile

Github use PR author as author...

fix the github name showing PR author problem in Jenkinsfile

---

Jenkinsfile

Deep customization of messages

use slack webhook

---

src/components/ArticleList.vue
src/components/list/ListArticleBlock.vue
src/util/comm.js
src/views/List.vue

- adjust getHref common utility for campaign style articles
- simplify ArticleList component structure
- filter duplicate articles in List component

fix Campaign Link Bug & adjust ArticleList Component

---

src/components/LatestArticleMain.vue
src/util/visibleTracking.js
src/views/404.ejs
src/views/404.vue
src/views/Activity.vue
src/views/Article.vue
src/views/ArticleM.vue
src/views/Home.vue
src/views/HomeB.vue
src/views/List.vue
src/views/Search.vue
src/views/TimelineView.vue
src/views/Topic.vue

- replace GA page param to location param
- add location param to GA visible event

adjust GA Page View & Event

---

.eslintrc
build/setup-dev-server.js
build/webpack.client.config.js
server.js
src/entry-client.js
src/entry-server.js

only show loading bar when there are matching asyncData hooks

enable redirecting on server

---

Jenkinsfile

this branch deploy to dev cluster as well.

Update dev branch Jenkinsfile

---

api/index.js
src/components/GroupList.vue
src/store/index.js
src/views/List.vue
src/views/Topic.vue

- add GroupList Component for Topic Group Style
- improve fetchArticleByUID Store Mechanism
- remove Newsletter API Port

add Topic Group Style & adjust fetchArticleByUUID Store

---

src/views/Home.vue

Have the url go with parameter ab like: `http://www.mirrormedia.mg?ab=a`.

client can decide role a or b through parameter ab = a || b

---

api/index.js

Notice: have to set `REDIS_CONNECTION_TIMEOUT: 2000` in config.js

instead of checking redis server, check if it is timeout

---

api/index.js

**NOTICE**
Have to set the following properties in `api/config.js` on production.
```
{
...
REDIS_RECOMMEND_NEWS_HOST: '',
REDIS_RECOMMEND_NEWS_PORT: '6379'
}
```

Fetch recommend news from specific redis

---

src/components/LiveStream.vue
src/components/article/ArticleBodyExternal.vue
src/views/External.vue
src/views/Home.vue
test/e2e/specs/home.spec.js

remove mod ab test on homepage
revise homepage e2e test

add google recomend articles to external page

---

api/index.js
src/components/article/RelatedListWithRecommendList.vue
src/constants/index.js
src/util/comm.js
src/views/Article.vue
src/views/ArticleM.vue
test/unit/specs/RelatedListWithRecommendList.spec.js

* kick component RelatedListWithRecommendList off
* insert recommends to relateds on article page
* add RelatedListWithRecommendList test
* complete RelatedListWithRecommendList test and do trimming

insert recommends to relateds on article page (#768)

---

src/components/ArticleList.vue
src/components/Header.vue
src/components/list/ListArticleBlock.vue
src/constants/dfpUnit.js
src/views/Topic.vue

- adjust list style and dfp LPCFT style
- adjust topic style
- hide external section

adjust list style and hide external section

---

Jenkinsfile
api/middle/story/middle.js
server.js
src/index.template.html
src/util/mixinTitleMeta.js
src/views/Article.vue
src/views/amp/index.amp.ejs

This reverts commit 200ffd816531266c8cb47fd0a515dce7d19234d7.

Revert "revert adTrace change (#870)"

---

src/components/list/ListSlider.vue
src/views/List.vue

Reverts mirror-media/plate-vue#923

Revert "update grand-seiko category style"

---

src/components/EditorChoice.vue
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyLayout.vue
src/components/article/RelatedListInContent.vue

- adjust article brief style
- adjust article related style
- adjust article related position when has a tag in content end
- use new gtm rule in `EditorChoice`

adjust article style and fix editor choice issue

---

src/components/FeaturedStoryFoodTravel.vue
src/components/LatestArticleAsideMobileB.vue
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyForApp.vue
src/components/article/PopList.vue
src/components/article/PopListVert.vue
src/components/article/ProjectList.vue
src/components/article/RecommendList.vue
src/util/comm.js
tests/unit/util/comm.test.js

- update `getBrief` unit test
- add `getHref` unit test
- clean unnecessary code

update utility test (getHref) and clean unnecessary code

---

src/components/ArticleListFull.vue
src/components/Share.vue
src/components/article/ArticleBodyPhotography.vue
src/components/article/ArticleBodyPhotographyForApp.vue
src/util/comm.js
tests/unit/util/comm.test.js

- add `getHrefFull` unit test
- add `getImage` unit test
- add `getSection` unit test
- clean unnecessary code

update utility test and clean unnecessary code

---

src/components/HeaderR.vue
src/components/LatestArticleMain.vue
src/components/article/ArticleBody.vue
src/components/article/ArticleBodyLayout.vue
src/router/index.js
src/store/index.js
src/util/comm.js
src/views/Article.vue
src/views/External.vue
src/views/Home.vue
src/views/List.vue
src/views/Search.vue
src/views/Topic.vue
src/views/Video.vue

- add Header ab test
- renew home page ab test
- remove article page ab test
- fix fetchLatestArticle bug in article page
- fix header logo dfp style issue

renew ab test and fix bugs

---

deprecated/ArticleLeading.vue
deprecated/EditorChoiceFull.vue
deprecated/LatestArticleFull.vue
src/components/EditorChoice.vue
src/components/EditorChoiceFoodTravel.vue
src/components/HeaderFull.vue
src/components/article/RecommendList.vue
src/util/comm.js
src/views/Activity.vue
src/views/Article.vue
src/views/ArticleM.vue
src/views/List.vue
src/views/Topic.vue
tests/unit/util/comm.test.js

- complete utility unit test
- change utility function `extractSlugFromreferrer` naming to `extractSlugFromReferrer`
- adjust test variables naming
- clean unnecessary code

complete utility unit test

---

src/util/comm.js
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue
src/views/Home.vue
src/views/List.vue
src/views/Video.vue
tests/unit/util/comm.test.js

- update utility test
- clean unused utility function `enableScroll `
- clean unnecessary code in `updateCookie`

update utility test

---

package.json
src/store/api.js
src/util/comm.js
tests/unit/store/api.test.js

- simplify store api
- add `buildUrlWithQuery` unit test

simplify store api

---

package.json
src/store/actions.js
src/store/getters.js
src/store/mutations.js
tests/unit/store/getters.test.js
tests/unit/store/mutations.test.js

- add store getters unit test
- clean unused store action `FETCH_EDITORCHOICE`
- clean unused store mutation `SET_USER`

add store getters unit test and clean unused store

---

.babelrc
package-lock.json
package.json
src/components/HeaderR.vue
src/store/actions.js
src/store/api.js
src/store/getters.js
src/store/index.js
src/store/mutations.js
src/util/comm.js
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue
src/views/Home.vue
src/views/List.vue
src/views/Search.vue
src/views/Topic.vue
src/views/Video.vue
tests/unit/store/api.test.js
tests/unit/store/getters.test.js
tests/unit/store/mutations.test.js
tests/unit/util/comm.test.js

This reverts commit 154c6fbaae41cc8204558b0dc6e0d815cb6d4db5.

Revert "revert commits (#1136)"

---

package-lock.json
src/store/actions.js
src/store/getters.js
src/store/index.js
src/store/mutations.js
src/util/comm.js
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue
src/views/Home.vue
src/views/List.vue
src/views/Video.vue
tests/unit/util/comm.test.js

- restructure store state (#1119)
- restructure vuex store (#1118)
- update utility test (#1110)

update utility test and restructure vuex store

---

src/components/article/ArticleBody.vue
src/components/article/ArticleBodyForApp.vue
src/components/article/ArticleBodyLayout.vue
src/components/audioPlayer/Player.vue
src/components/audioPlayer/PlayerInfo.vue
src/constants/dfpUnit.js
src/views/Article.vue
src/views/ArticleM.vue

- adjust mobile article style 
- adjust dfp position in mobile article
- adjust fetchArticles param in `articleM`
- add dfp unit id for app article page

adjust mobile article style and dfp position

---

src/components/LatestArticleMain.vue
src/components/MicroAd.vue
src/components/article/ArticleBody.vue
src/components/article/LatestList.vue
src/components/article/PopList.vue
src/components/article/PopListVert.vue
src/components/article/RecommendList.vue
src/views/ArticleM.vue

- recover app page dfp mode
- adjust article page link target setting
- fix app page dfp ft style

recover app dfp mode and adjust article page link target setting

---

src/components/PopInAd.vue
src/components/article/RecommendList.vue
src/util/comm.js
src/views/Article.vue

This reverts commit a2c349d3de25246dfb2b9e5bf3deab6d9728fd38.

add back popin ads

---

src/components/article/LatestList.vue
src/components/article/RecommendList.vue
src/components/article/RelatedListInContent.vue
src/util/comm.js
src/views/Article.vue
src/views/ArticleM.vue

- update article ab test (dable recommend)
- fix article link in app page
- adjust heading in related list

update article ab test and fix issues

---

api/middle/redisHandler.js

- replace redis connection pool by node_redis
- replace `TimeoutHandler` by `promiseTimeout`
- use same retry strategy
- remove duplicate time period log in `fetchFromRedisForAPI`

replace redis connection pool by node_redis

---

package-lock.json
package.json
src/App.vue
src/app.js
src/entry-server.js
src/index.template.html
src/router/index.js
src/views/404.vue
src/views/Activity.vue
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue
src/views/Headline.vue
src/views/Home.vue
src/views/List.vue
src/views/Search.vue
src/views/TimelineView.vue
src/views/Topic.vue
src/views/Video.vue

- use vue-meta to process page head meta
- use vue-meta to process article page JSON-LD

use vue-meta to process page head meta

---

api/middle/ioredisHandler.js
src/components/article/ArticleAsideFixed.vue
src/components/article/ArticleBodyExternal.vue
src/components/article/LatestList.vue
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue
src/views/Topic.vue

- fix article page not correct to page 404 issue
- fix app article page not correct to page 404 issue
- fix topic page not correct to page 404 issue
- fix external article page not correct to page 404 issue
- fix external listing page not show latest list issue
- fix article aside error in external article page
- adjust external article page fb comment style
- remove unnecessary redis log

fix error 500 page issue

---

.babelrc
.eslintrc
amp/service/middle.js
amp/service/util.js
package-lock.json
package.json
postcss.config.js

- add `cssnano` for minify css
- remove `@babel/polyfill`
- update babel and eslint packages version

add cssnano for minify css and update babel setting

---

src/views/Article.vue

This reverts commit 0576d07b6bdb7d6f3b441f35d8e022b706d61885.

Revert "test popIn ad in article (#1346)"

---

src/components/EditorChoice.vue

- add EditorChoice link trace query
- simplify component

feat: add EditorChoice link trace query

---

src/components/article/ArticleBody.vue
src/components/article/ArticleBodyExternal.vue
src/components/article/RelatedListInContent.vue
src/views/Article.vue
src/views/ArticleM.vue
src/views/External.vue

- add `RelatedListInContent` ab test in article page
- remove the latest list in article page (previous ab test result)

feat: add RelatedListInContent ab test in article page

---

src/components/article/ArticleAsideFixed.vue
src/components/article/ArticleBodyExternal.vue
src/views/Article.vue
src/views/External.vue

- switch READr embedded and FB page in `ArticleAsideFixed`
- adjust trigger point in `ArticleAsideFixed.vue`
- combine `fbPage` and `fbPage-External` slot

feat: switch READr embedded and FB page in ArticleAsideFixed

---

src/components/article/RelatedListInContent.vue
src/views/Article.vue

This reverts commit b8f4c4fc3f9192e91f14c1488466ac1e9a3f0514.

Revert "feat(abTest): add another style to RelatedListInContent"

---

src/components/article/ArticleBody.vue
src/components/article/ShareTools.vue
src/util/comm.js
src/views/Article.vue

This reverts commit [b895bc4](https://github.com/mirror-media/plate-vue/commit/b895bc4d388e49c8fc19619a8dd1304f5ef1fbfb) and [e63dcd4](https://github.com/mirror-media/plate-vue/commit/e63dcd450d03b9123c10ec7747e2182502ce8e6d)

revert: for infinite scroll

---

src/store/index.js
src/views/Home.vue

- set `asyncData` error fallback
- throw not found error when fetching specific data happened error
- fix `FETCH_LATESTARTICLES ` unexpected undefined error

fix(Home): set asyncData error fallback

---

src/components/LatestArticleMain.vue
src/components/article/ArticleBodyExternal.vue
src/components/article/RecommendList.vue
src/components/header/HeaderNav.vue
src/components/header/HeaderSidebar.vue
src/constants/index.js
src/util/comm.js
src/views/Home.vue
src/views/amp/styles/StoryInfo.css

- insert externals articles in latest
- change external color `#ee5a24` to `#fb9d18`

feat(home): insert externals articles in latest

---

src/components/article/RelatedListInContent.vue
src/constants/microAds.js
src/views/Article.vue

- use correct microAd id on the article page
- adjust microAd style on the desktop article page

feat(microAd): use correct microAd id on article page

---

src/components/header/HeaderNav.vue

This reverts commit 31b769dae22cb6f165149432ea50f6178fec0011.

Revert "feat(videohub): rollback to oath video page (#1500)"
